[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Q3uUS0RZH-deTWIAQeOVbJ4AdNH90zQN)

### NumPy Arrays
- NumPy array are by default Homogeneous, which means data inside an array must be of the same Datatype. 
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.


In [2]:
import numpy as np
print(np.__version__)

1.19.5


In [3]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
type(np.zeros(3))

numpy.ndarray

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
np.zeros(3).shape

(3,)

In [12]:
np.zeros((3,2)).shape

(3, 2)

In [13]:
np.zeros(3).ndim

1

In [15]:
np.zeros((3,2)).ndim

2

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.array([[1,2,3,4],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
np.linspace(0,4.5,10)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [60]:
n= 1000000 
a = np.random.rand(n)
b = np.random.rand(n)

In [61]:
import time 
"""
Record multiple running times.
"""
class Timer: 
    def __init__(self):
        self.times = []

    def start(self):
        self.tik = time.time()
    
    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]

In [62]:
timer = Timer()

timer.start()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
timer.stop()

timer.start()
c = a + b
timer.stop()

0.003704547882080078

In [63]:
timer.times

[0.622638463973999, 0.003704547882080078]

In [64]:
print("speedup is: %s" % (timer.times[0]/timer.times[1]))

speedup is: 168.07407645771656


In [65]:
a = np.array([[1,2,3,4],[10,20,30,40]])
print(a)

[[ 1  2  3  4]
 [10 20 30 40]]


In [66]:
b = a.reshape(4,2)
print(b)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [67]:
b[0,1] = -1

In [68]:
print(b)

[[ 1 -1]
 [ 3  4]
 [10 20]
 [30 40]]


In [69]:
print(a)

[[ 1 -1  3  4]
 [10 20 30 40]]


In [70]:
c = np.array([3,4,5,6,7,8,9])

In [71]:
c > 6

array([False, False, False, False,  True,  True,  True])

In [72]:
c[c>6]

array([7, 8, 9])